name: 'Send Mail'
description: 'Send Email By Nodemailer'
author: 'XiaoMuCOOL <xiaomucool@bingblue.com>'
branding:
  icon: mail
  color: red
inputs: 
  myInput2:
    description: 'Input to use'
    default: 'world'
  myinput:
    description: 'Input to use'
    default: 'world22'
runs:
  using: 'docker'
  image: 'Dockerfile'
