name: 'Send Mail'
description: 'Send Email By Nodemailer'
author: 'XiaoMuCOOL <xiaomucool@bingblue.com>'
branding:
  icon: mail
  color: red
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
  myInput2:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
